name: PopolServer
author: Nathan Fallet
main: me.nathanfallet.popolserver.PopolServer
load: STARTUP
version: 1.0
api-version: 1.16
commands:
    leaderboard:
        description: Gérer les classements
        permission: popolserver.leaderboard
    menu:
        description: Afficher le menu pour changer de serveur
    money:
        description: Actualiser et afficher son compte
    spawn:
        description: Se teleporter au spawn
    setspawn:
        description: Definir le point de spawn
        permission: popolserver.setspawn
