name: PopolServer
version: 1.0
author: Nathan Fallet
main: me.nathanfallet.popolserver.PopolServer
api-version: 1.16
commands:
    leaderboards:
        description: Gérer les classements
        permission: popolserver.leaderboards
    menu:
        description: Afficher le menu pour changer de serveur
    money:
        description: Actualiser et afficher son compte
    spawn:
        description: Se teleporter au spawn
    setspawn:
        description: Definir le point de spawn
        permission: popolserver.setspawn
